<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="dfb338ad-9474-486d-b534-ecb8c59f4f83" name="Bruno@BRUNO-PC 2012-02-15 13:58:49" runUser="Bruno-PC\Bruno" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="ca88e069-f008-4408-aa18-24caa99d89f1">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Bruno_BRUNO-PC 2012-02-15 13_58_49">
      <DeploymentItem filename="C:\Program Files\Moq.4.0.10827\NET40\Moq.dll" />
      <DeploymentItem filename="C:\projetos\ta\TA\Source\TA.Domain\bin\Debug\TA.Domain.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-02-15T13:58:49.0230589-02:00" queuing="2012-02-15T13:59:03.5310844-02:00" start="2012-02-15T13:59:03.8742850-02:00" finish="2012-02-15T13:59:54.1531733-02:00" />
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" error="0" failed="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Incluir_Anunciante_Invalido_Retorna_Exception_5_Erros" storage="c:\projetos\ta\ta\source\ta.domain.test\bin\debug\ta.domain.test.dll" id="545fe080-d106-5011-7889-9699ff26684d">
      <Execution id="f0feb088-d2d5-4b84-93ee-1228725f8de4" />
      <TestMethod codeBase="C:/projetos/ta/TA/Source/TA.Domain.Test/bin/Debug/TA.Domain.Test.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TA.Domain.Test.Service.ServicoAnuncianteTest, TA.Domain.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Incluir_Anunciante_Invalido_Retorna_Exception_5_Erros" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="545fe080-d106-5011-7889-9699ff26684d" executionId="f0feb088-d2d5-4b84-93ee-1228725f8de4" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="f0feb088-d2d5-4b84-93ee-1228725f8de4" testId="545fe080-d106-5011-7889-9699ff26684d" testName="Incluir_Anunciante_Invalido_Retorna_Exception_5_Erros" computerName="BRUNO-PC" duration="00:00:46.8434073" startTime="2012-02-15T13:59:04.1550855-02:00" endTime="2012-02-15T13:59:53.8567728-02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="f0feb088-d2d5-4b84-93ee-1228725f8de4">
    </UnitTestResult>
  </Results>
</TestRun>